Add support for PHP 8
FoolCode/SphinxQL-Query-Builder pull request #197
Opened 2021-01-22 10:02 UTC by ben221199

This PR adds support for PHP 8.

2021-01-22 10:02 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/8556b51b-cce7-4569-b41b-30e29b960885) was created.

2021-01-22 10:10 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/8556b51b-cce7-4569-b41b-30e29b960885) completed: **11 new issues, 22 updated code elements**

2021-01-22 10:31 UTC, ben221199 commented
Seems Travis is hanging.

2021-01-22 11:16 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/824aeb31-5250-4bd1-ada8-12110aa6432e) was created.

2021-01-22 11:18 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/824aeb31-5250-4bd1-ada8-12110aa6432e) completed: **22 updated code elements**

2021-01-31 10:46 UTC, Gemorroj commented on composer.json
> +        "php": "^5.6|^7.0|^8"
use `||` instead `|`. see https://github.com/composer/composer/issues/6755

2021-01-31 10:46 UTC, Gemorroj commented on composer.json
> +        "phpunit/phpunit": "^5.7|^6|^7|^8|^9"
use || instead |. see composer/composer#6755

2021-01-31 11:23 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/d8bb7062-aed1-46ba-9243-a45035ae1684) was created.

2021-01-31 11:23 UTC, ben221199 commented on composer.json
> +        "php": "^5.6|^7.0|^8"
Fixed in next commit.

2021-01-31 11:23 UTC, ben221199 commented on composer.json
> +        "phpunit/phpunit": "^5.7|^6|^7|^8|^9"
Fixed in next commit.

2021-01-31 11:30 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/d8bb7062-aed1-46ba-9243-a45035ae1684) completed: **22 updated code elements**

2021-01-31 22:45 UTC, mfjordvald commented
Would be great to get this merged in.

2021-02-03 14:31 UTC, ben221199 commented
@Gemorroj Changes are made. Where are we waiting for?

2021-02-03 14:35 UTC, Gemorroj commented
@ben221199 im not maintainer of that project) im waiting the change like you

2021-02-03 14:51 UTC, ben221199 commented
> @ben221199 im not maintainer of that project) im waiting the change like you
Ah okay.
@oohnoitz I see that you did merge PRs in the past. Could you also check this one?

2021-02-03 15:13 UTC, woxxy commented
We need to get the CI to work first, will look into it when I have some time

2021-02-03 15:24 UTC, oohnoitz requested changes

2021-02-03 15:24 UTC, oohnoitz commented on CHANGELOG.md
> +* added `orPhrase` method to `MatchBuilder` class
this should be reverted and added under as a breaking change for 3.x or whatever version is the bump. i'm not exactly sure but have a feeling that some people may be extending or using this `Match` class manually.

```
#### 3.0.0

* added support for PHP 8.x
* renamed `Foolz\SphinxQL\Match` to `Foolz\SphinxQL\MatchBuilder` (BREAKING CHANGE)
```

2021-02-03 15:25 UTC, oohnoitz commented
just had a tiny nit regarding the CHANGELOG modifications. but we'll need to look into the CI as @woxxy mentioned.

2021-02-03 16:19 UTC, ben221199 commented on CHANGELOG.md
> +* added `orPhrase` method to `MatchBuilder` class
Fixed in next commit.

2021-02-05 23:04 UTC, ben221199 commented
The last version was `2.1.0`, so the next version could be `2.1.1`, `2.2.0` or `3.0.0`. Because we add support for PHP 8, I would say the best choice is to go to `3.0.0`. I also used that version in the Change Log.

2021-02-07 22:54 UTC, oohnoitz commented
Next version would be 3.0.0 since renaming would be a breaking change. Also, don't see the change pushed up yet.

2021-02-08 14:51 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/bbb6d229-f7aa-4078-bbd6-c7374a9be7f1) was created.

2021-02-08 14:52 UTC, ben221199 commented
Well, that was stupid :D.
I pushed it now.

2021-02-08 15:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/bbb6d229-f7aa-4078-bbd6-c7374a9be7f1) completed: **22 updated code elements**

2021-02-09 00:34 UTC, oohnoitz requested changes
there are a few nits regarding code style inconsistency. also, can you fix the travis builds so it passes?

2021-02-09 00:34 UTC, oohnoitz commented on tests/SphinxQL/TestUtil.php
> +$GLOBALS['driver'] = 'Mysqli';
can you revert this change? we have the CI set up to test both `Mysqli` and `Pdo` drivers.

2021-02-09 00:34 UTC, oohnoitz commented on tests/SphinxQL/SphinxQLTest.php
> +//        $result = $this->createSphinxQL()
any specific reason why this was removed?

2021-02-09 00:34 UTC, oohnoitz commented on tests/SphinxQL/ConnectionTest.php
> +    protected function setUp(): void{
the `void` return type is causing php 5.6 tests to fail. same with all of the other cases this change was made in.

also code style should be followed. curly braces should be on a new line instead and not sure why tabs and spaces is being mixed.

2021-02-09 00:34 UTC, oohnoitz commented on tests/SphinxQL/HelperTest.php
> +            $this->createHelper()->showTables('rt')->execute()->fetchAllAssoc()
any reason why `getStored()` was switch to `fetchAllAssoc()`?

2021-02-09 08:40 UTC, ben221199 commented on tests/SphinxQL/TestUtil.php
> +$GLOBALS['driver'] = 'Mysqli';
Yes. I did do this to get testing working locally.

2021-02-09 08:41 UTC, ben221199 commented
> there are a few nits regarding code style inconsistency. also, can you fix the travis builds so it passes?

Is there also a reason why I cannot see the Travis CI build?

2021-02-09 08:50 UTC, ben221199 commented on tests/SphinxQL/HelperTest.php
> +            $this->createHelper()->showTables('rt')->execute()->fetchAllAssoc()
Because `getStored()` is deprecated.

2021-02-09 08:57 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/70480f53-093d-4825-942a-464c1057ae6f) was created.

2021-02-09 08:58 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/70480f53-093d-4825-942a-464c1057ae6f) completed: **1 new issues, 22 updated code elements**

2021-02-09 09:04 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/8b83e1f0-a85a-4f65-80d5-db5b1c235e29) was created.

2021-02-09 09:05 UTC, ben221199 commented on tests/SphinxQL/ConnectionTest.php
> +    protected function setUp(): void{
Fixed now.

2021-02-09 09:06 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/8b83e1f0-a85a-4f65-80d5-db5b1c235e29) completed: **22 updated code elements**

2021-02-09 09:07 UTC, ben221199 commented on tests/SphinxQL/SphinxQLTest.php
> +//        $result = $this->createSphinxQL()
Because `$result` was directly overwritten by the next query. I should fix this by only removing the `$result = ` part.

2021-02-09 09:10 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/c4cfae39-71d0-4f9a-a1d1-80737193aec4) was created.

2021-02-09 09:12 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/c4cfae39-71d0-4f9a-a1d1-80737193aec4) completed: **22 updated code elements**

2021-02-09 09:35 UTC, ben221199 commented
> > there are a few nits regarding code style inconsistency. also, can you fix the travis builds so it passes?
> 
> Is there also a reason why I cannot see the Travis CI build?

Never mind. This was an issue in my browser.

2021-02-09 09:40 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/9fc3b1d7-a90a-48ff-8b31-69182a1d1cc0) was created.

2021-02-09 09:42 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/9fc3b1d7-a90a-48ff-8b31-69182a1d1cc0) completed: **22 updated code elements**

2021-02-09 09:45 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/f2c606ad-8eae-4366-bef6-655ff98716f1) was created.

2021-02-09 09:47 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/f2c606ad-8eae-4366-bef6-655ff98716f1) completed: **22 updated code elements**

2021-02-10 09:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/721074d5-5806-46f7-8e4b-acac9be9df46) was created.

2021-02-10 09:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/721074d5-5806-46f7-8e4b-acac9be9df46) completed: **22 updated code elements**

2021-02-10 09:46 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/0b0c8aa6-102a-4403-8466-6e1d69fca834) was created.

2021-02-10 09:48 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/0b0c8aa6-102a-4403-8466-6e1d69fca834) completed: **1 new issues, 22 updated code elements**

2021-02-10 11:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/7444b3e2-87c8-4046-acb2-8a5c7b9aeaa8) was created.

2021-02-10 11:06 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/7444b3e2-87c8-4046-acb2-8a5c7b9aeaa8) completed: **1 new issues, 22 updated code elements**

2021-02-10 11:11 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/fa01f3ce-6cf3-4710-98b7-76b300d8f9c6) was created.

2021-02-10 11:13 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/808c2f28-d87d-4e74-9876-cad9f41d6012) was created.

2021-02-10 11:13 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/fa01f3ce-6cf3-4710-98b7-76b300d8f9c6) completed: **1 new issues, 22 updated code elements**

2021-02-10 11:14 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/808c2f28-d87d-4e74-9876-cad9f41d6012) completed: **22 updated code elements**

2021-02-10 11:48 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/1737c6ce-c1c8-433e-b331-48f128995434) was created.

2021-02-10 11:50 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/1737c6ce-c1c8-433e-b331-48f128995434) completed: **3 new issues, 24 updated code elements**

2021-02-10 11:55 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/c4ae85a8-d2ba-46e6-b9f9-20692c5a5527) was created.

2021-02-10 11:57 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/c4ae85a8-d2ba-46e6-b9f9-20692c5a5527) completed: **4 new issues, 24 updated code elements**

2021-02-10 12:03 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/8820c77e-6b13-4f66-a48f-58a12ec62c19) was created.

2021-02-10 12:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/8820c77e-6b13-4f66-a48f-58a12ec62c19) completed: **3 new issues, 26 updated code elements**

2021-02-10 12:26 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/903a9ccc-ca9c-4d2a-a92d-bb0114aa6b12) was created.

2021-02-10 12:28 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/903a9ccc-ca9c-4d2a-a92d-bb0114aa6b12) completed: **26 updated code elements**

2021-02-10 12:28 UTC, Gemorroj commented
@ben221199 probably use https://github.com/FriendsOfPHP/PHP-CS-Fixer to fix code style issues. It not pass psr1/psr2/psr12 standards at this moment

2021-02-10 12:39 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/ad5ee8fd-a741-445b-b9ff-e22a96746426) was created.

2021-02-10 12:39 UTC, ben221199 commented
> @ben221199 probably use https://github.com/FriendsOfPHP/PHP-CS-Fixer to fix code style issues. It not pass psr1/psr2/psr12 standards at this moment

Yes, I have that one to fix the style, but there are also some issues that cannot be fixed with that one.

2021-02-10 12:40 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/ad5ee8fd-a741-445b-b9ff-e22a96746426) completed: **1 new issues, 26 updated code elements**

2021-02-10 12:42 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/5d360b9d-172b-4e21-b204-01b649aa0d02) was created.

2021-02-10 12:44 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/5d360b9d-172b-4e21-b204-01b649aa0d02) completed: **1 new issues, 26 updated code elements**

2021-02-10 12:46 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/ba18523d-eaae-4d80-8fd1-8695accf9c69) was created.

2021-02-10 12:47 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/ba18523d-eaae-4d80-8fd1-8695accf9c69) completed: **26 updated code elements**

2021-02-10 13:45 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/f21b78ce-1477-406e-96b3-57f5aa1a4473) was created.

2021-02-10 13:47 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/f21b78ce-1477-406e-96b3-57f5aa1a4473) completed: **26 updated code elements**

2021-02-10 13:52 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/4a83903c-eedc-40a5-a053-96b7848f7641) was created.

2021-02-10 13:54 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/4a83903c-eedc-40a5-a053-96b7848f7641) completed: **26 updated code elements**

2021-02-10 13:56 UTC, ben221199 commented
@woxxy Why is Auto Cancellation off?

2021-02-10 15:39 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/28ab8e1c-c955-4195-aacc-99f032b9034e) was created.

2021-02-10 15:41 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/28ab8e1c-c955-4195-aacc-99f032b9034e) completed: **26 updated code elements**

2021-02-10 18:55 UTC, ben221199 commented
Some tests are failing now. How do I fix that?

2021-02-11 12:11 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/eacb28a8-eaf4-43a7-a801-c54be573f463) was created.

2021-02-11 12:12 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/eacb28a8-eaf4-43a7-a801-c54be573f463) completed: **26 updated code elements**

2021-02-11 14:04 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/0df2f659-0c12-4a4b-a136-18417ad3b4c8) was created.

2021-02-11 14:06 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/0df2f659-0c12-4a4b-a136-18417ad3b4c8) completed: **26 updated code elements**

2021-02-11 18:18 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/39942850-f160-4037-b143-d67290225526) was created.

2021-02-11 18:20 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/39942850-f160-4037-b143-d67290225526) completed: **26 updated code elements**

2021-02-11 20:17 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/eb90e2fa-41bb-4b61-83ad-e79726333405) was created.

2021-02-11 20:19 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/eb90e2fa-41bb-4b61-83ad-e79726333405) completed: **26 updated code elements**

2021-02-12 11:31 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/0b1cc719-c6e1-4801-bc5b-5d0d1b7070fb) was created.

2021-02-12 11:32 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/0b1cc719-c6e1-4801-bc5b-5d0d1b7070fb) completed: **26 updated code elements**

2021-02-12 11:43 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/91296362-6e25-4b24-89fa-a5b7bf06fc01) was created.

2021-02-12 11:45 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/91296362-6e25-4b24-89fa-a5b7bf06fc01) completed: **28 updated code elements**

2021-02-12 18:01 UTC, ben221199 commented
Lets merge this now we have a passing Travis build. If we merge this to another branch (instead of `FoolCode:master`), I could make new tests in another PR. I vote for `FoolCode:php8`.

2021-02-13 10:53 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/359d24f3-b5f2-4b68-a59a-debf02e1bf49) was created.

2021-02-13 10:54 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/359d24f3-b5f2-4b68-a59a-debf02e1bf49) completed: **113 updated code elements**

2021-02-13 11:01 UTC, ben221199 reviewed
Perfect.

2021-02-13 11:33 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/6140d846-6d62-48a3-ab7d-84edcf8e5467) was created.

2021-02-13 11:34 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/6140d846-6d62-48a3-ab7d-84edcf8e5467) completed: **113 updated code elements**

2021-02-13 11:39 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/7f9cc868-cd8e-46f3-9282-819e4ec036fc) was created.

2021-02-13 11:41 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/7f9cc868-cd8e-46f3-9282-819e4ec036fc) completed: **113 updated code elements**

2021-02-13 11:44 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/f7e565ea-ddb0-4904-a386-fa947f98c827) was created.

2021-02-13 11:46 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/f7e565ea-ddb0-4904-a386-fa947f98c827) completed: **113 updated code elements**

2021-02-13 11:52 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/058314bc-652d-4198-95db-60cacec14cfb) was created.

2021-02-13 11:53 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/058314bc-652d-4198-95db-60cacec14cfb) completed: **113 updated code elements**

2021-02-13 12:41 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/aec55908-a5bd-456a-953e-ba5545e949ec) was created.

2021-02-13 12:42 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/aec55908-a5bd-456a-953e-ba5545e949ec) completed: **114 updated code elements**

2021-02-15 20:56 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/fb8c989f-3355-43c9-ae4b-3fa2e8daa750) was created.

2021-02-15 21:03 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/fb8c989f-3355-43c9-ae4b-3fa2e8daa750) completed: **1 new issues, 116 updated code elements**

2021-02-15 21:43 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/ab24428e-7063-4198-b8ac-b99842dd8aa2) was created.

2021-02-15 21:44 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/ab24428e-7063-4198-b8ac-b99842dd8aa2) completed: **116 updated code elements**

2021-02-15 21:54 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/adce7f61-25af-4e84-aade-6ea95b120a85) was created.

2021-02-15 21:56 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/adce7f61-25af-4e84-aade-6ea95b120a85) completed: **117 updated code elements**

2021-02-15 22:05 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/275cdcc9-e971-4b0f-9844-84b5e12bc317) was created.

2021-02-15 22:07 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/275cdcc9-e971-4b0f-9844-84b5e12bc317) completed: **117 updated code elements**

2021-02-15 22:14 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/cfef0e1a-7ced-4cbc-809a-ed77e44ae298) was created.

2021-02-15 22:15 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/FoolCode/SphinxQL-Query-Builder/inspections/cfef0e1a-7ced-4cbc-809a-ed77e44ae298) completed: **117 updated code elements**

2021-02-15 22:25 UTC, ben221199 commented
@oohnoitz Is there anything possible at the moment?

2021-02-16 00:57 UTC, oohnoitz reviewed
it's taking me some time to determine what actual changes were made and review them. i'm seeing a few tests that are commented out. is the plan to fix them in a subsequent PR? if that is the case, we can get the current work merged into a branch on this repo and have some follow up PRs done to fix the broken tests. otherwise, i can't go ahead and merge it in as-is since this is removing tests.

2021-02-16 01:06 UTC, oohnoitz reviewed
leaving a few comments to track down missing/removed tests. and determine what went wrong. adding php8 support should have caused those tests to break at all.

2021-02-16 01:06 UTC, oohnoitz commented on tests/Drivers/MultiResultSetTest.php
> +//    /**
`MultiResultSet` test was removed for some reason?

2021-02-16 01:06 UTC, oohnoitz commented on tests/FacetTest.php
> +//	public static $DATA = [
this can be removed if it isn't used at all in the test file.

2021-02-16 01:06 UTC, oohnoitz commented on tests/HelperTest.php
> +    //		$this->createHelper()->createFunction('my_udf', 'INT', 'test_udf.so')->execute();
`createFunction` test was removed for some reason?

2021-02-16 01:06 UTC, oohnoitz commented on tests/PercolateTest.php
> +//    /**
Manticore Percolate test file was removed for some reason?

2021-02-16 01:06 UTC, oohnoitz commented on tests/SphinxQLTest.php
> +    //	public function testUpdate(): void
`update` tests were removed for some reason.

2021-02-16 01:06 UTC, oohnoitz commented on tests/SphinxQLTest.php
> +//        $this->assertEquals('11', $result[2][0]['id'] ?? null);
what's happening here? it should default to `null`

2021-02-16 01:06 UTC, oohnoitz commented on tests/SphinxQLTest.php
> +//            $result = $this->createSphinxQL()
facet tests were removed for some reason? also not sure why we are returning early for `Mysqli` driver.

2021-02-16 10:10 UTC, ben221199 commented on tests/SphinxQLTest.php
> +//            $result = $this->createSphinxQL()
> it's taking me some time to determine what actual changes were made and review them. i'm seeing a few tests that are commented out. is the plan to fix them in a subsequent PR? if that is the case, we can get the current work merged into a branch on this repo and have some follow up PRs done to fix the broken tests. otherwise, i can't go ahead and merge it in as-is since this is removing tests.

I think that is the easiest thing to do now.

2021-02-16 10:10 UTC, ben221199 commented
> it's taking me some time to determine what actual changes were made and review them. i'm seeing a few tests that are commented out. is the plan to fix them in a subsequent PR? if that is the case, we can get the current work merged into a branch on this repo and have some follow up PRs done to fix the broken tests. otherwise, i can't go ahead and merge it in as-is since this is removing tests.

I think that is the easiest thing to do now.

2021-02-16 17:02 UTC, merged

2021-02-16 17:02 UTC, oohnoitz commented
@ben221199 merged it into `php8` branch so that it can be worked on there.

2021-02-17 09:49 UTC, ben221199 commented
Nice. I will try to work on that one. But if other people feel free to help, they are welcome :D

2021-04-08 15:42 UTC, red-led commented
Tried updating to `php8` branch in my code (`composer require foolz/sphinxql-query-builder dev-php8`) and getting this error:
```
mysqli_sql_exception: Commands out of sync; you can't run this command now .../foolz/sphinxql-query-builder/src/Drivers/Mysqli/Connection.php:151
Stack trace:
#0 .../foolz/sphinxql-query-builder/src/Drivers/Mysqli/Connection.php(151): mysqli->multi_query()
#1 .../foolz/sphinxql-query-builder/src/SphinxQL.php(296): Foolz\SphinxQL\Drivers\Mysqli\Connection->multiQuery()
...
```

Is it bug or BC?

If I just manually rename `Match` to `MathBuilder` in old version - it works on php8 without any problems.

2021-04-08 17:09 UTC, ben221199 commented
@red-led What version do you use? Sphinx 2, Sphinx 3 or MantiCore?

2021-04-08 17:11 UTC, red-led commented
@ben221199, Sphinx 2

2021-04-09 21:51 UTC, ben221199 commented
Did you try Sphinx 3?

2021-04-11 15:32 UTC, ben221199 commented
**Update:**
See https://github.com/FoolCode/SphinxQL-Query-Builder/pull/198